CREATE TABLE IF NOT EXISTS Customers (
    Email VARCHAR(100) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Last_Name VARCHAR(50) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Password VARCHAR(255) NOT NULL
);