CREATE TABLE IF NOT EXISTS purchase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reference VARCHAR(36) UNIQUE NOT NULL,
    purchase_date TIMESTAMP NOT NULL,
    ticket_amount INT NOT NULL,
    total DECIMAL(10,2) NOT NULL
);